// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxnzcvjyqghisjmmmiwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4bnpjdmp5cWdoaXNqbW1taXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1Nzc5NjYsImV4cCI6MjA1NTE1Mzk2Nn0.4FQOxD_KhB2vddGs4MQkG8o111ij6uOkGqhey6Wc6YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);